name: open_bootcamp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: "Yellowtail"
      fonts:
        - asset: assets/fonts/Yellowtail-Regular.ttf

  assets:
    - assets/
    - assets/fonts/
    - assets/images/