image: gitpod/workspace-base

tasks:
  - name: Setup workspace
    command: |
      cd $HOME
      sudo wget https://netcologne.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
      sudo apt update --allow-insecure-repositories -y
      sudo apt upgrade -y
      sudo apt -y --allow-unauthenticated install --reinstall d-apt-keyring
      sudo apt update -y
      sudo apt install -y dmd-compiler dmd-tools dmd-doc dub
      git clone https://github.com/Pure-D/serve-d.git
      cd serve-d
      dub build
      sudo cp serve-d /usr/local/bin/
      cd ..
      rm -rf serve-d

vscode:
  extensions:
    - webfreak.code-d