image: gitpod/workspace-base

tasks:
  - name: Setup workspace
    command: |
      sudo apt update
      sudo apt upgrade -y
      sudo apt install -y apt-transport-https
      sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
      sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
      sudo apt update
      sudo apt install -y dart

vscode:
  extensions:
    - dart-code.dart-code