name: flutter_notes
description: "OpenBootcamp Flutter course notes"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sprintf: ^7.0.0
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  image_picker: ^1.0.7
  # image_picker_for_web: ^3.0.2
  location: ^6.0.2
  http: ^1.2.1
  provider: ^6.1.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: "Yellowtail"
      fonts:
        - asset: assets/fonts/Yellowtail-Regular.ttf

  assets:
    - assets/
    - assets/fonts/
    - assets/images/