name: flutter_notes
description: "OpenBootcamp Flutter course notes"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sprintf: ^7.0.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  provider: ^6.1.1
  flutter:
    sdk: flutter
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: "Yellowtail"
      fonts:
        - asset: assets/fonts/Yellowtail-Regular.ttf

  assets:
    - assets/
    - assets/fonts/
    - assets/images/