image: gitpod/workspace-base

tasks:
  - name: Setup workspace
    command: |
      sudo wget https://netcologne.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
      sudo apt update --allow-insecure-repositories -y
      sudo apt upgrade -y
      sudo apt -y --allow-unauthenticated install --reinstall d-apt-keyring
      sudo apt update -y
      sudo apt install -y dmd-compiler dmd-tools dmd-doc dub python3-pip
      sudo pip3 install -U meson ninja

vscode:
  extensions:
    - webfreak.code-d
    - asabil.meson